create schema if not exists attribute;

create table if not exists attribute.attributes(
    id int generated by default as identity primary key ,
    title varchar(40) not null
);

create table if not exists attribute.attribute_options(
    id int generated by default as identity primary key ,
    value varchar(40) not null ,
    attribute_id int references attribute.attributes(id) on delete cascade not null ,
    product_type_id int not null
);

create table if not exists attribute.product_attribute_assignments(
    id int generated by default as identity primary key ,
    product_id int not null,
    product_type_attribute_value_id int references attribute.attribute_options(id) not null
);

--- 1 - get
--- 2 - update
--- 3 - delete Не ставить в REFERENCES

-- ---------- Attributes ----------

-- Test: AttributeTests get()
-- Описание: атрибут для проверки метода получения по id
INSERT INTO attribute.attributes (title) VALUES('Color');

-- Test: AttributeTests update()
-- Описание: атрибут для проверки метода обновления
INSERT INTO attribute.attributes (title) VALUES('Size');

-- Test: AttributeTests delete()
-- Описание: атрибут для проверки метода удаления
INSERT INTO attribute.attributes (title) VALUES('Material');

-- Синхронизируем sequence с текущим max(id)
SELECT setval('attribute.attributes_id_seq', (SELECT MAX(id) FROM attribute.attributes));

-- ---------- Product Type Attribute Values ----------

-- Test: ProductTypeAttributeValueTests get
-- Описание: значение атрибута типа продукта для проверки получения
INSERT INTO attribute.attribute_options (attribute_id, product_type_id, value)
VALUES (1, 1, 'Size');

-- Test: ProductTypeAttributeValueTests update
-- Описание: значение атрибута типа продукта для проверки обновления
INSERT INTO attribute.attribute_options (attribute_id, product_type_id, value)
VALUES (1, 1, 'Color');

-- Test: ProductTypeAttributeValueTests delete
-- Описание: значение атрибута типа продукта для проверки удаления
INSERT INTO attribute.attribute_options (attribute_id, product_type_id, value)
VALUES (1, 1, 'Material');

-- Синхронизируем sequence с текущим max(id)
SELECT setval('attribute.attribute_options_id_seq', (SELECT MAX(id) FROM attribute.attribute_options));

-- ---------- Product Attribute Values ----------

-- Test: ProductAttributeAssignmentTests get()
-- Описание: значение атрибута продукта для проверки метода получения по id
INSERT INTO attribute.product_attribute_assignments (product_id, product_type_attribute_value_id) VALUES
    (1, 1);

-- Test: ProductAttributeAssignmentTests update()
-- Описание: значение атрибута продукта для проверки метода обновления
INSERT INTO attribute.product_attribute_assignments (product_id, product_type_attribute_value_id) VALUES
    (2, 1);

-- Test: ProductAttributeAssignmentTests delete()
-- Описание: значение атрибута продукта для проверки метода удаления
INSERT INTO attribute.product_attribute_assignments (product_id, product_type_attribute_value_id) VALUES
    (3, 1);

-- Синхронизируем sequence с текущим max(id)
SELECT setval('attribute.product_attributes_id_seq', (SELECT MAX(id) FROM attribute.product_attribute_assignments));