create schema if not exists attribute;

create table if not exists attribute.attributes(
                                                   id int generated by default as identity primary key ,
                                                   title varchar(40) not null
);

create table if not exists attribute.product_attribute_values(
                                                                 id int generated by default as identity primary key ,
                                                                 value varchar(40) not null ,
                                                                 attribute_id int references attribute.attributes(id) on delete cascade ,
                                                                 product_id int not null
);


create table if not exists attribute.product_type_attribute_values(
                                                                      id int generated by default as identity primary key ,
                                                                      value varchar(40) not null ,
                                                                      attribute_id int references attribute.attributes(id) on delete cascade ,
                                                                      product_type_id int not null
);

--- 1 - get
--- 2 - update
--- 3 - delete Не ставить в REFERENCES

-- ---------- Attributes ----------

-- Test: AttributeTests get()
-- Описание: атрибут для проверки метода получения по id
INSERT INTO product.attributes (title) VALUES('Color');

-- Test: AttributeTests update()
-- Описание: атрибут для проверки метода обновления
INSERT INTO product.attributes (title) VALUES('Size');

-- Test: AttributeTests delete()
-- Описание: атрибут для проверки метода удаления
INSERT INTO product.attributes (title) VALUES('Material');

-- Синхронизируем sequence с текущим max(id)
SELECT setval('product.attributes_id_seq', (SELECT MAX(id) FROM product.attributes));


-- ---------- Product Attribute Values ----------

-- Test: ProductAttributeValueTests get()
-- Описание: значение атрибута продукта для проверки метода получения по id
INSERT INTO product.product_attribute_values (attribute_id, product_id, value) VALUES
    (1, 1, 'Red');

-- Test: ProductAttributeValueTests update()
-- Описание: значение атрибута продукта для проверки метода обновления
INSERT INTO product.product_attribute_values (attribute_id, product_id, value) VALUES
    (2, 1, 'Medium');

-- Test: ProductAttributeValueTests delete()
-- Описание: значение атрибута продукта для проверки метода удаления
INSERT INTO product.product_attribute_values (attribute_id, product_id, value) VALUES
    (2, 2, 'Cotton');

-- Синхронизируем sequence с текущим max(id)
SELECT setval('product.product_attribute_values_id_seq', (SELECT MAX(id) FROM product.product_attribute_values));

-- ---------- Product Type Attribute Values ----------

-- Test: ProductTypeAttributeValueTests get
-- Описание: значение атрибута типа продукта для проверки получения
INSERT INTO product.product_type_attribute_values (attribute_id, product_type_id, value)
VALUES (1, 1, 'Size');

-- Test: ProductTypeAttributeValueTests update
-- Описание: значение атрибута типа продукта для проверки обновления
INSERT INTO product.product_type_attribute_values (attribute_id, product_type_id, value)
VALUES (1, 1, 'Color');

-- Test: ProductTypeAttributeValueTests delete
-- Описание: значение атрибута типа продукта для проверки удаления
INSERT INTO product.product_type_attribute_values (attribute_id, product_type_id, value)
VALUES (1, 1, 'Material');

-- Синхронизируем sequence с текущим max(id)
SELECT setval('product.product_type_attribute_values_id_seq', (SELECT MAX(id) FROM product.product_type_attribute_values));