create schema if not exists attribute;

create table if not exists attribute.attributes(
    id int generated by default as identity primary key ,
    title varchar(40) not null
);

create table if not exists attribute.attribute_options(
    id int generated by default as identity primary key ,
    value varchar(40) not null ,
    attribute_id int references attribute.attributes(id) on delete cascade not null ,
    product_type_id int not null
);

create table if not exists attribute.product_attribute_assignments(
    id int generated by default as identity primary key ,
    product_id int not null,
    attribute_option_id int references attribute.attribute_options(id) not null
);