create schema if not exists attribute;

create table if not exists attribute.attributes(
    id int generated by default as identity primary key ,
    title varchar(40) not null
);

create table if not exists attribute.product_attribute_values(
    id int generated by default as identity primary key ,
    value varchar(40) not null ,
    attribute_id int references attribute.attributes(id) on delete cascade ,
    product_id int not null
);


create table if not exists attribute.product_type_attribute_values(
    id int generated by default as identity primary key ,
    value varchar(40) not null ,
    attribute_id int references attribute.attributes(id) on delete cascade ,
    product_type_id int not null
);