create schema if not exists attribute;

create table if not exists attribute.attributes(
    id int generated by default as identity primary key ,
    title varchar(40) not null
);

create table if not exists attribute.product_type_attribute_values(
    id int generated by default as identity primary key ,
    value varchar(40) not null ,
    attribute_id int references attribute.attributes(id) on delete cascade not null ,
    product_type_id int not null
);

create table if not exists attribute.product_attributes(
    id int generated by default as identity primary key ,
    product_id int not null,
    product_type_attribute_value_id int references attribute.product_type_attribute_values(id) not null
);